PulsarStore.Language:Language("es", 1)
    :Plural("argument")("Argumento")("Argumentos")()
    :Plural("credit")("Crédito")("Créditos")()
    :Plural("item")("Objeto")("Objetos")()

    -- Generic
    :Set("brand", "Tienda Pulsar")
    :Set("admin", "Admin.")
    :Set("yes", "Sí")
    :Set("no", "No")
    :Set("unknown", "Desconocido/a")
    :Set("alreadyown", "Ya tienes este objeto.")
    :Set("owned", "Adquirido")
    :Set("permanent", "Permanente")
    :Set("cancel", "Cancelar")
    :Set("purchase", "Adquirir")
    :Set("buy", "Comprar")
    :Set("sell", "Vender")
    :Set("credit", "{{plural:credit|creditsCount}}")
    :Set("credits", "Créditos")
    :Set("money", "Dinero")
    :Set("close", "Cerrar")
    :Set("return", "Regresar")
    :Set("enable", "Habilitar")
    :Set("enabled", "Habilitado")
    :Set("disable", "Deshabilitar")
    :Set("disabled", "Deshabilitado")
    :Set("item", "{{plural:objeto|cantidad}}")

    -- Errors
    :Set("error.permissions", "Permisos insuficientes")
    :Set("error.permissions.message", "No tienes permiso para realizar eso.")
    :Set("error.ratelimit", "Estás enviando demasiadas solicitudes. Por favor espera unos segundos e inténtalo de nuevo.")
    :Set("error.unknown", "¡Ocurrió un error!")
    :Set("error.unexpected", "¡Ocurrió un error inesperado!")
    :Set("error.maxconvert", "¡Has alcanzado el límite diario de conversión de {{credits}} créditos!")
    :Set("error.cannotafford", "¡No puedes pagar esto!")
    :Set("error.cannotafford.currency", "No tienes suficiente/s {{currency}} para adquirir este paquete!")
    :Set("error.notfound", "¡El objeto que estás intentando comprar no existe!")
    :Set("error.alreadyown", "¡Ya tienes este objeto!")
    :Set("error.ownwholebundle", "¡Ya tienes todos los objetos de este paquete!")

    -- Main Menu
    :Set("mainmenu.home", "Inicio")
    :Set("mainmenu.inventory", "Inventario")
    :Set("mainmenu.credits.buymore", "Comprar créditos")
    :Set("search", "Buscar...")
    :Set("search.hidepurchased", "Ocultar comprados")

    -- Items
    :Set("item.discountprice", "{{oldprice}} {{newprice}} {{plural:credit|creditsCount}}")
    :Set("item.percentoff", "¡{{percent}}% de descuento!")
    :Set("item.whatsincluded", "Incluye:")
    :Set("item.bundle.creditstext", "{{credits}} - Paquete")
    :Set("item.price", "{{price}} {{plural:credit|creditsCount}}")

    -- Categories
    :Set("admin.categories", "Categorías")
    :Set("admin.categories.create", "Crear Categoría")
    :Set("admin.categories.create.name", "Nombre")
    :Set("admin.categories.create.name.placeholder", "Mi Categoría")
    :Set("admin.categories.create.icon", "Ícono")
    :Set("admin.categories.create.color", "Color")
    :Set("admin.categories.create.create", "Crear")
    :Set("admin.categories.create.noname", "El nombre no puede estar vacío")
    :Set("admin.categories.create.noicon", "El ícono no puede estar vacío")
    :Set("admin.categories.create.success", "¡Categoría creada!")
    :Set("admin.categories.create.failed", "Error al crear la categoría: {{err}}")
    :Set("admin.categories.edit", "Editar categoría")
    :Set("admin.categories.edit.edit", "Editar")
    :Set("admin.categories.edit.noname", "El nombre no puede estar vacío")
    :Set("admin.categories.edit.noicon", "El ícono no puede estar vacío")
    :Set("admin.categories.edit.success", "¡Categoría creada exitosamente!")
    :Set("admin.categories.edit.failed", "Error al editar la categoría: {{err}}")
    :Set("admin.categories.delete", "Eliminar Categoría")
    :Set("admin.categories.delete.success", "¡Categoría eliminada exitosamente!")
    :Set("admin.categories.delete.failed", "Error al eliminar la categoría: {{err}}")
    :Set("admin.categories.delete.confirm", "¿Estás seguro de que deseas eliminar esta categoría?")

    -- Packages
    :Set("admin.packages", "Paquetes")
    :Set("admin.packages.create", "Crear Paquete")
    :Set("admin.packages.create.name", "Nombre")
    :Set("admin.packages.create.name.placeholder", "Mi paquete")
    :Set("admin.packages.create.price", "Precio")
    :Set("admin.packages.create.currency", "Divisa")
    :Set("admin.packages.create.permanent", "¿Es permanente?")
    :Set("admin.packages.create.icon", "Ícono")
    :Set("admin.packages.create.category", "Categoría")
    :Set("admin.packages.create.color", "Color")
    :Set("admin.packages.create.next", "Siguiente")
    :Set("admin.packages.create.actions", "Nueva Acción de Paquete")
    :Set("admin.packages.create.actions.argument", "{{plural:argument|count}}")
    :Set("admin.packages.create.create", "Crear")
    :Set("admin.packages.edit", "Editar paquete")
    :Set("admin.packages.edit.edit", "Editar")
    :Set("admin.packages.edit.delete", "Eliminar")
    :Set("admin.packages.create.success", "¡Paquete creado exitosamente!")
    :Set("admin.packages.create.failed", "Error al crear el paquete.")
    :Set("admin.packages.edit.success", "¡Paquete editado exitosamente!")
    :Set("admin.packages.edit.failed", "Error al editar el paquete.")
    :Set("admin.packages.delete.success", "¡Paquete eliminado exitosamente!")
    :Set("admin.packages.delete.failed", "Error al eliminar el paquete.")

    -- Bundles
    :Set("admin.bundles", "Conjuntos")
    :Set("admin.bundles.create", "Crear Conjunto")
    :Set("admin.bundles.create.name", "Nombre")
    :Set("admin.bundles.create.name.placeholder", "Mi Conjunto")
    :Set("admin.bundles.create.price", "Precio")
    :Set("admin.bundles.create.currency", "Divisa")
    :Set("admin.bundles.create.icon", "Ícono")
    :Set("admin.bundles.create.category", "Categoría")
    :Set("admin.packages.create.color", "Color")
    :Set("admin.bundles.create.next", "Siguiente")
    :Set("admin.bundles.create.bundlepackage", "Nuevo Paquete de Conjuntos")
    :Set("admin.bundles.create.create", "Crear")
    :Set("admin.bundles.edit", "Editar conjunto")
    :Set("admin.bundles.edit.edit", "Editar")
    :Set("admin.bundles.edit.delete", "Eliminar")
    :Set("admin.bundles.create.success", "¡Conjunto creado exitosamente!")
    :Set("admin.bundles.create.failed", "Error al crear el conjunto.")
    :Set("admin.bundles.edit.success", "¡Conjunto editado exitosamente!")
    :Set("admin.bundles.edit.failed", "Error al editar el conjunto.")

    -- Discounts
    :Set("percentoff", "¡{{percent}}% de descuento!")
    :Set("discount", "Descuento")
    :Set("admin.discounts", "Descuentos")
    :Set("admin.discounts.delete", "Eliminar Descuentos")
    :Set("admin.discounts.delete.confirm", "¿Estás seguro de que deseas eliminar este descuento?")
    :Set("admin.discounts.create", "Crear Descuento")
    :Set("admin.discounts.create.amount", "Cantidad")
    :Set("admin.discounts.create.enddate", "Fecha de Finalización")
    :Set("admin.discounts.create.failed", "Error al crear el descuento.")
    :Set("admin.discounts.create.success", "¡Descuento creado exitosamente!")
    :Set("admin.discounts.items", "Objetos en descuento")
    :Set("admin.discounts.save", "Guardar")
    :Set("admin.discounts.items.add", "Añadir Objeto")
    :Set("admin.discounts.items.add.success", "¡Objeto añadido exitosamente!")
    :Set("admin.discounts.items.add.failed", "Error al agregar el objeto.")
    :Set("admin.discounts.items.remove.success", "¡Objeto removido exitosamente!")
    :Set("admin.discounts.items.remove.failed", "Error al remover el objeto.")

    -- Users
    :Set("admin.users", "Usuarios")
    :Set("admin.users.remove", "Remover")
    :Set("admin.users.remove.success", "¡Compra removida exitosamente!")
    :Set("admin.users.add.success", "¡Compra añadida exitosamente!")

    :Set("admin.home", "Inicio")

    -- Other
    :Set("periodic", "¡Has sido recompensado con {{creditsCount}} {{plural:credit|creditsCount}} por jugar en el servidor!")
    :Set("spawnprop", "No cuentas con el paquete necesario para generar este/a {{type}}.")
    :Set("purchasetooold", "No puedes regresar el paquete debido a que fue comprado hace más de {{time}} días.")
    :Set("success.purchase", "¡El/La{{item}} fue comprado exitosamente!")
    :Set("success.convert.money", "¡Has convertido {{arg1}} a {{arg2}} créditos!")
    :Set("success.convert.credits", "¡Has convertido {{arg1}} a {{arg2}} dinero!")
:Register()
