PulsarStore.Language:Language("pt-BR", 1)
    :Plural("argument")("Argumento")("Argumentos")()
    :Plural("credit")("Crédito")("Créditos")()
    :Plural("item")("Item")("Itens")()

-- Generic
    :Set("brand", "Loja Pulsar")
    :Set("admin", "Admin")
    :Set("yes", "Sim")
    :Set("no", "Não")
    :Set("unknown", "Desconhecido")
    :Set("alreadyown", "Você já possuí este item.")
    :Set("owned", "Adquirido")
    :Set("permanent", "Permanente")
    :Set("cancel", "Cancelar")
    :Set("purchase", "Comprar") 
    :Set("buy", "Comprar") -- Non ironically purchase and buy is the same word in Brazillian Portuguese xD
    :Set("sell", "Vender")
    :Set("credit", "{{plural:credit|creditsCount}}")
    :Set("credits", "Créditos")
    :Set("money", "Dinheiro")
    :Set("close", "Fechar")
    :Set("return", "Voltar")
    :Set("enable", "Habilitar")
    :Set("enabled", "Habilitado")
    :Set("disable", "Desabilitar")
    :Set("disabled", "Desabilitado")
    :Set("item", "{{plural:item|count}}")

-- Errors
    :Set("error.permissions", "Permissões insuficientes")
    :Set("error.permissions.message", "Você não tem permissão para fazer isso.")
    :Set("error.ratelimit", "Você está enviando muitas requisições. Por favor, espere alguns segundos e tente novamente.")
    :Set("error.unknown", "Um erro desconhecido ocorreu!")
    :Set("error.unexpected", "Um erro inesperado ocorreu!")
    :Set("error.maxconvert", "Você atingiu o limite de conversão diária de {{credits}} créditos. Você pode converter mais {{allowed}} créditos hoje!")
    :Set("error.cannotafford", "Você não pode pagar por isso!")
    :Set("error.cannotafford.currency", "Você não tem {{currency}} suficiente para comprar este pacote!")
    :Set("error.notfound", "O item que você está tentando comprar não existe!")
    :Set("error.alreadyown", "Você já tem este item!")
    :Set("error.ownwholebundle", "Você já tem todos os itens deste conjunto!")

-- Main Menu
    :Set("mainmenu.home", "Início")
    :Set("mainmenu.inventory", "Inventário")
    :Set("mainmenu.credits.buymore", "Comprar mais créditos")
    :Set("search", "Pesquisar...")
    :Set("search.hidepurchased", "Ocultar adquiridos")

-- Items
    :Set("item.discountprice", "{{oldprice}} {{newprice}} {{plural:credit|creditsCount}}")
    :Set("item.percentoff", "{{percent}}% de desconto!")
    :Set("item.whatsincluded", "O que está incluído:")
    :Set("item.bundle.creditstext", "{{credits}} - Conjunto")
    :Set("item.price", "{{price}} {{plural:credit|creditsCount}}")

-- Categories
    :Set("admin.categories", "Categorias")
    :Set("admin.categories.create", "Criar categoria")
    :Set("admin.categories.create.name", "Nome")
    :Set("admin.categories.create.name.placeholder", "Minha categoria")
    :Set("admin.categories.create.icon", "Ícone")
    :Set("admin.categories.create.color", "Cor")
    :Set("admin.categories.create.create", "Criar")
    :Set("admin.categories.create.noname", "Nome não pode estar vazio")
    :Set("admin.categories.create.noicon", "Ícone não pode estar vazio")
    :Set("admin.categories.create.success", "Categoria criada com sucesso!")
    :Set("admin.categories.create.failed", "Falha ao criar categoria: {{err}}")
    :Set("admin.categories.edit", "Editar categoria")
    :Set("admin.categories.edit.edit", "Editar")
    :Set("admin.categories.edit.noname", "Nome não pode estar vazio")
    :Set("admin.categories.edit.noicon", "Ícone não pode estar vazio")
    :Set("admin.categories.edit.success", "Categoria editada com sucesso!")
    :Set("admin.categories.edit.failed", "Falha ao editar categoria: {{err}}")
    :Set("admin.categories.delete", "Excluir categoria")
    :Set("admin.categories.delete.success", "Categoria excluída com sucesso!")
    :Set("admin.categories.delete.failed", "Falha ao excluir categoria: {{err}}")
    :Set("admin.categories.delete.confirm", "Tem certeza que quer excluir esta categoria?")

-- Packages
    :Set("admin.packages", "Pacotes")
    :Set("admin.packages.create", "Criar pacotes")
    :Set("admin.packages.create.name", "Nome")
    :Set("admin.packages.create.name.placeholder", "Meu pacote")
    :Set("admin.packages.create.price", "Preço")
    :Set("admin.packages.create.currency", "Moeda")
    :Set("admin.packages.create.permanent", "Permanente?")
    :Set("admin.packages.create.icon", "Ícone")
    :Set("admin.packages.create.category", "Categoria")
    :Set("admin.packages.create.color", "Cor")
    :Set("admin.packages.create.next", "Próximo")
    :Set("admin.packages.create.actions", "Nova ação de pacote")
    :Set("admin.packages.create.actions.argument", "{{plural:argument|count}}")
    :Set("admin.packages.create.create", "Criar")
    :Set("admin.packages.edit", "Editar pacote")
    :Set("admin.packages.edit.edit", "Editar")
    :Set("admin.packages.edit.delete", "Excluir")
    :Set("admin.packages.create.success", "Pacote criado com sucesso!")
    :Set("admin.packages.create.failed", "Falha ao criar pacote.")
    :Set("admin.packages.edit.success", "Pacote editado com sucesso!")
    :Set("admin.packages.edit.failed", "Falha ao editar pacote.")
    :Set("admin.packages.delete.success", "Pacote excluído com sucesso!")
    :Set("admin.packages.delete.failed", "Falha ao excluir pacote.")

-- Bundles
    :Set("admin.bundles", "Conjuntos")
    :Set("admin.bundles.create", "Criar conjunto")
    :Set("admin.bundles.create.name", "Nome")
    :Set("admin.bundles.create.name.placeholder", "Meu conjunto")
    :Set("admin.bundles.create.price", "Preço")
    :Set("admin.bundles.create.currency", "Moeda")
    :Set("admin.bundles.create.icon", "Ícone")
    :Set("admin.bundles.create.category", "Categoria")
    :Set("admin.bundles.create.color", "Cor")
    :Set("admin.bundles.create.next", "Próximo")
    :Set("admin.bundles.create.bundlepackage", "Novo conjunto de pacotes")
    :Set("admin.bundles.create.create", "Criar")
    :Set("admin.bundles.edit", "Editar conjunto")
    :Set("admin.bundles.edit.edit", "Editar")
    :Set("admin.bundles.edit.delete", "Excluir")
    :Set("admin.bundles.create.success", "Conjunto criado com sucesso!")
    :Set("admin.bundles.create.failed", "Falha ao criar conjunto.")
    :Set("admin.bundles.edit.success", "Conjunto editado com sucesso!")
    :Set("admin.bundles.edit.failed", "Falha ao editar conjunto.")

-- Discounts
    :Set("percentoff", "{{percent}}% de desconto!")
    :Set("discount", "Desconto")
    :Set("admin.discounts", "Descontos")
    :Set("admin.discounts.delete", "Excluir desconto")
    :Set("admin.discounts.delete.confirm", "Tem certeza que quer excluir esse desconto?")
    :Set("admin.discounts.create", "Criar desconto")
    :Set("admin.discounts.create.amount", "Quantidade")
    :Set("admin.discounts.create.enddate", "Data de término")
    :Set("admin.discounts.create.failed", "Falha ao criar desconto.")
    :Set("admin.discounts.create.success", "Desconto criado com sucesso!")
    :Set("admin.discounts.items", "Itens com desconto")
    :Set("admin.discounts.save", "Salvar")
    :Set("admin.discounts.items.add", "Adicionar item")
    :Set("admin.discounts.items.add.success", "Item adicionado com sucesso!")
    :Set("admin.discounts.items.add.failed", "Falha ao criar item.")
    :Set("admin.discounts.items.remove.success", "Item removido com sucesso!")
    :Set("admin.discounts.items.remove.failed", "Falha ao remover item.")

-- Users
    :Set("admin.users", "Usuários")
    :Set("admin.users.remove", "Remover")
    :Set("admin.users.remove.success", "Compra removida com sucesso!")
    :Set("admin.users.add.success", "Compra adicionada com sucesso!")

    :Set("admin.home", "Voltar ao início")

-- Other
    :Set("periodic", "Você foi recompensado com {{creditsCount}} {{plural:credit|creditsCount}} por jogar no servidor!")
    :Set("spawnprop", "Você não possuí o pacote necessário para criar este(a) {{type}}.")
    :Set("purchasetooold", "Você não pode reembolsar esta compra pois comprou há mais de {{time}} dias atrás.")
    :Set("success.purchase", "Comprou {{item}} com sucesso!")
    :Set("success.convert.money", "Você converteu ${{arg1}} para {{arg2}} créditos!")
    :Set("success.convert.money.left", "Você converteu ${{arg1}} para {{arg2}} créditos. Você pode converter mais {{allowed}} créditos hoje!")
    :Set("success.convert.credits", "Você converteu {{arg1}} para {{arg2}} em dinheiro!")
:Register()
